# -*- coding: utf-8 -*-
"""Scenario_Day16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SzcuUA5y4mBLl50838Uui0Nit2wAxJDH
"""

# Scenario: Fitness & Wellness Chatbot Training
# You feed it these sentences:
# - “Push-ups strengthen chest and triceps”
# - “Yoga improves flexibility and balance”
# - “Apples are rich in fiber”
# - “Cardio exercises boost heart health”
# 👉 In this case, the chatbot learns to distinguish between exercise facts, nutrition facts, and general wellness statements, so it can tailor its responses — e.g., suggesting workouts, offering diet tips, or explaining health benefits.
# Would you like me to design a third scenario (maybe in education or travel) so you have a set of examples across different industries?

# Install required library
# pip install sentence-transformers

from sentence_transformers import SentenceTransformer
import numpy as np

# Step 1: Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Step 2: Training sentences (knowledge base)
sentences = [
    "Push-ups strengthen chest and triceps",
    "Yoga improves flexibility and balance",
    "Apples are rich in fiber",
    "Cardio exercises boost heart health"
]

# Step 3: Convert sentences to embeddings
embeddings = model.encode(sentences)

# Step 4: Function to find most similar sentence
def chatbot_response(query):

    query_embedding = model.encode([query])

    # Calculate similarity
    similarity = np.dot(embeddings, query_embedding.T)

    # Find best match
    index = np.argmax(similarity)

    return sentences[index]

# Step 5: Chatbot interaction
query = input("Ask a health question: ")

response = chatbot_response(query)

print("Chatbot Suggestion:", response)

# Scenario: Healthcare Chatbot – Patient Symptom Matching
# Imagine you’re designing a healthcare chatbot that helps patients find possible conditions based on their symptoms. Both patients and conditions are represented as vectors of features (e.g., fever, cough, fatigue, headache).
# - Patient’s symptom vector:
# [0.2,0.8,-0.3,0.5] → mild fever, strong cough, no fatigue, moderate headache.
# - Condition’s symptom profile vector:
# [0.1,0.9,-0.2,0.4] → mild fever, strong cough, little fatigue, moderate headache.
# The chatbot uses cosine similarity to measure how closely the patient’s symptoms align with the condition’s profile

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Patient symptom vector
# fever, cough, fatigue, headache
patient_vector = np.array([[0.2, 0.8, -0.3, 0.5]])

# Condition symptom profile vector
condition_vector = np.array([[0.1, 0.9, -0.2, 0.4]])

# Calculate cosine similarity
similarity = cosine_similarity(patient_vector, condition_vector)

print("Patient Symptom Vector:", patient_vector)
print("Condition Symptom Vector:", condition_vector)
print("Cosine Similarity Score:", similarity[0][0])

# Interpretation
if similarity[0][0] > 0.8:
    print("High similarity: Symptoms strongly match the condition.")
elif similarity[0][0] > 0.5:
    print("Moderate similarity: Possible condition match.")
else:
    print("Low similarity: Symptoms do not strongly match.")

# Scenario: Warehouse Robot Navigation
# Imagine a warehouse where a robot needs to pick up items.
# - The robot is currently at position (1,2) on the warehouse grid.
# - The item it needs to collect is stored at position (4,6).
# The robot’s navigation system calculates the straight-line distance to the item so it knows how far it must travel if it moves directly.

import math

# Robot current position
robot_x = 1
robot_y = 2

# Item position
item_x = 4
item_y = 6

# Calculate Euclidean distance
distance = math.sqrt((item_x - robot_x)**2 + (item_y - robot_y)**2)

print("Robot Position:", (robot_x, robot_y))
print("Item Position:", (item_x, item_y))
print("Straight-line Distance to Item:", round(distance, 2))

# Scenario: Basketball Player Evaluation
# A coach is evaluating how well a player’s skills match the team’s current needs.
# - The team’s requirement vector is a = [2,5,1].
# - 2 = need for shooting ability
# - 5 = need for defense
# - 1 = need for passing
# - The player’s skill vector is b = [3,4,2].
# - 3 = player’s shooting ability
# - 4 = defensive ability
# - 2 = passing ability
# The coach calculates the dot product:

#Scenario: Basketball Player Evaluation

import numpy as np

# vectors
a = np.array([2, 5, 1])
b = np.array([3, 4, 2])

# dot product
dot_product = np.dot(a, b)

print("Dot Product:", dot_product)

# # 🛒 Scenario: E‑Commerce Product Recommendations
# # Imagine you’re building a smart recommendation engine for an online store.
# # - Problem: Customers often search with phrases like “comfortable running shoes”,
#  but the catalog has items
# #  titled “lightweight sneakers for jogging”. Traditional keyword
#  search struggles to connect these.
# # - Solution: Use embeddings to capture semantic meaning of product
# descriptions and customer queries.

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# 🛒 Customer query embedding (semantic meaning of "comfortable running shoes")
query_embedding = np.array([0.1, 0.8, 0.5])

# 📦 Product catalog embeddings (semantic meaning of product descriptions)
product_embeddings = {
    "lightweight sneakers for jogging": np.array([0.2, 0.7, 0.6]),
    "formal leather shoes": np.array([0.9, 0.1, 0.2]),
    "sandals for summer": np.array([0.3, 0.4, 0.5])
}

# 🔍 Compute similarity between query and each product
for product, embedding in product_embeddings.items():
    similarity = np.dot(query_embedding, embedding)  # fast similarity check
    cosine_sim = cosine_similarity([query_embedding], [embedding])[0][0]  # normalized similarity
    print(f"{product} → Dot Product: {similarity:.3f}, Cosine Similarity: {cosine_sim:.3f}")

# ✅ Recommendation: pick the product with highest similarity
best_match = max(product_embeddings.items(), key=lambda x: np.dot(query_embedding, x[1]))
print("\nRecommended Product:", best_match[0])

# 🎓 Scenario: Online Learning Platform Recommendations
# Imagine you’re building a smart recommendation engine for an online education platform.
# - Problem: Students often search with phrases like “beginner-friendly Python tutorials”, but the course
# catalog has items titled “Introduction to Programming with Python”. Traditional keyword search struggles to
# connect these because the words don’t match exactly.
# - Solution: Use embeddings to capture the semantic meaning of both student queries and course descriptions.
# By comparing embeddings with dot product or cosine similarity, the system can recommend the most relevant
# courses even when the wording is different

#online learning platform
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Example embeddings (normally generated using models like BERT)
query_embedding = np.array([0.2, 0.8, 0.5])

course_embeddings = {
    "Introduction to Programming with Python": np.array([0.3, 0.75, 0.45]),
    "Advanced Data Structures in Java": np.array([0.9, 0.1, 0.2]),
    "Machine Learning Basics": np.array([0.4, 0.6, 0.7])
}

# Calculate similarity
for course, emb in course_embeddings.items():
    similarity = cosine_similarity([query_embedding], [emb])[0][0]
    print(course, "-> Similarity:", similarity)

# Scenario: Hospital FAQ Assistant
# A hospital wants to build a chatbot that helps patients quickly find answers to common questions.
# - Problem: Patients ask questions in different ways. For example:
# - “How do I book an appointment?”
# - “What’s the process to schedule a doctor visit?”
# - “Can I see a physician tomorrow?”
# Traditional keyword search might miss these connections.
# - Solution: Convert FAQs and patient queries into embeddings, then measure similarity to find the closest match.

# 👩‍💻 Code in Context

# Install first if needed:
# pip install sentence-transformers scikit-learn

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Step 1: Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Step 2: Hospital FAQ database
faq_questions = [
    "How do I book an appointment?",
    "What are the hospital visiting hours?",
    "How can I contact a doctor?",
    "Where is the emergency department located?",
    "What documents are required for admission?"
]

faq_answers = [
    "You can book an appointment online through our hospital website or call the reception.",
    "Visiting hours are from 10 AM to 6 PM every day.",
    "You can contact a doctor through the hospital helpline or patient portal.",
    "The emergency department is located on the ground floor.",
    "You need an ID proof, insurance card, and previous medical records."
]

# Step 3: Convert FAQ questions to embeddings
faq_embeddings = model.encode(faq_questions)

# Step 4: Chatbot function
def hospital_chatbot(user_query):

    query_embedding = model.encode([user_query])

    # Compute similarity
    similarity = cosine_similarity(query_embedding, faq_embeddings)

    # Get best match
    best_match = similarity.argmax()

    return faq_answers[best_match]

# Step 5: User interaction
user_question = input("Ask your hospital question: ")

response = hospital_chatbot(user_question)

print("\nChatbot Answer:", response)

!pip install faiss-cpu  # Install faiss

#  Scenario: Package Delivery in a City
# Imagine you run a delivery company in a huge city with 100,000 houses. Each house has a
#  unique “address fingerprint” (like the 384‑dimensional vectors in your code).
# Now, when a customer places an order, you need to quickly find the nearest warehouse or
#  delivery hub to their house. Instead of checking every single house one by one (which would
# be very slow), you use smart strategies:

# 🗺️ HNSW (Hierarchical Navigable Small World)
# - Think of it like a layered city map:
# - Top layer = highways (coarse overview).
# - Middle layer = main roads.
# - Bottom layer = all streets and houses.
# - To find the nearest warehouse, you start at the highway level, zoom into the right district,
# then finally navigate down to the exact street.
# - This is what IndexHNSWFlat does: it builds a graph of connections so you can “hop” quickly
# to the right neighborhood.

# 🏘️ IVF (Inverted File Index)
# - Imagine dividing the city into 256 neighborhoods (Voronoi cells).
# - First, figure out which neighborhood the customer’s house belongs to.
# - Then, only search inside that neighborhood instead of the whole city.
# - This is what IndexIVFFlat does: it clusters vectors and searches only in the most relevant
# clusters.
# - nprobe = 10 means you don’t just check one neighborhood, but the 10 most likely ones —
#  balancing speed and accuracy.

# ⚡ In Plain Words
# - HNSW = zooming in layer by layer on a city map.
# - IVF = splitting the city into neighborhoods and searching locally.
# - Both methods help you find the closest match fast without scanning all 100,000 houses.





import faiss
import numpy as np

d = 384       # embedding dimension
n = 100_000   # number of vectors

# ── HNSW index ──────────────────────────────
index = faiss.IndexHNSWFlat(d, 32)  # M=32 neighbours
index.hnsw.efConstruction = 200     # build quality
index.hnsw.efSearch = 100           # query quality

vectors = np.random.randn(n, d).astype("float32")
faiss.normalize_L2(vectors)         # L2 normalize
index.add(vectors)                  # add all vectors

query = np.random.randn(1, d).astype("float32")
faiss.normalize_L2(query)
D, I = index.search(query, k=10)    # top-10
print("Indices:", I[0])             # [2341, 8712, ...]
print("Distances:", D[0])           # cosine scores

# ── IVF index (faster for large scale) ──────
nlist = 256   # number of Voronoi cells
quantizer = faiss.IndexFlatL2(d)
index_ivf = faiss.IndexIVFFlat(quantizer, d, nlist)
index_ivf.train(vectors)
index_ivf.add(vectors)
index_ivf.nprobe = 10               # cells to search

# Scenario: Student Course Recommendations
# Imagine you’re running an online learning platform. Students type queries like “beginner-friendly Python tutorials”,
# but your catalog has courses titled “Introduction to Programming with Python”.
# Traditional keyword search might miss the match, but embeddings + vector search (Chroma locally or Pinecone in the cloud)
#  can connect them semantically.

# 🧩 Teaching Exercise Flow
# - Documents (Courses)
# - "Python is a high-level programming language"
# - "Machine learning models need training data"
# - "Dogs are loyal and friendly animals"
# - "Cats are independent and curious pets"
# - Embedding Model
# - Converts each course description into a vector (numbers capturing meaning).
# - Indexing
# - Chroma (local): Great for classroom demos, no API key needed.
# - Pinecone (cloud): Scales to billions of items, perfect for production.
# - Query
# - Student asks: “What animals make good companions?”
# - Embedding of query is compared against course embeddings.
# - Results
# - Top matches:
# - Cats are independent and curious pets
# - Dogs are loyal and friendly animals

# OPTION A: Chroma (local, no API key needed)
!pip install chromadb
!pip install sentence-transformers
import chromadb
from sentence_transformers import SentenceTransformer

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Create Chroma client and collection
client = chromadb.Client()  # or chromadb.PersistentClient(path="./db")
collection = client.create_collection("docs")

# Sample documents
documents = [
    "Python is a high-level programming language",
    "Machine learning models need training data",
    "Dogs are loyal and friendly animals",
    "Cats are independent and curious pets",
]

# Encode documents into embeddings
embeddings = model.encode(documents).tolist()

# Add to Chroma collection
collection.add(
    documents=documents,
    embeddings=embeddings,
    ids=[f"doc{i}" for i in range(len(documents))],
    metadatas=[{"source": "demo", "idx": i} for i in range(len(documents))]
)

# Query with semantic search
query = "What animals make good companions?"
q_emb = model.encode([query]).tolist()
results = collection.query(query_embeddings=q_emb, n_results=3)

# Print results
for doc, dist in zip(results["documents"][0], results["distances"][0]):
    print(f"[{dist:.3f}] {doc}")